# Generated by Django 4.2.7 on 2024-08-13 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('apk_file_path', models.FileField(upload_to='apks/')),
                ('first_screen_screenshot_path', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
                ('second_screen_screenshot_path', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
                ('video_recording_path', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('ui_hierarchy', models.TextField(blank=True, null=True)),
                ('screen_changed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
