# Generated by Django 5.1 on 2024-08-20 19:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_app_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='apk_file_path',
            field=models.FileField(upload_to='media/apks/'),
        ),
        migrations.AlterField(
            model_name='app',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='app',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
