# Generated by Django 5.1 on 2024-08-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_app_apk_file_path_alter_app_id_alter_app_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='apk_file_path',
            field=models.FileField(upload_to='apks/'),
        ),
    ]
